### ISSUE TITLE
IDE Controller bad port selection

### ISSUE THREAD

**Issue by nwbugo** [kusnier/vagrant-persistent-storage#58]
Hi,
I see that in new release the default port for IDE Controller was changed to 4.
I know that it causes issues for some users, where IDE Controller only support ports 0 and 1.
I hope the problem will be addressed.
Cheers.

**Comment by jeffgeorge** [comment]
Seeing the same thing here with an Ubuntu 14.04 box.

```
==> default: ** Persistent Storage Volume exists, not creating **
==> default: ** Attaching persistent storage **
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "[guid-redacted]", "--storagectl", "IDE Controller", "--port", "4", "--device", "0", "--type", "hdd", "--medium", "/[path-redacted]/mysql.vdi"]

Stderr: VBoxManage: error: The port and/or device parameter are out of range: port=4 (must be in range [0, 1]), device=0 (must be in range [0, 1])
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component StorageControllerWrap, interface IStorageController, callee nsISupports
VBoxManage: error: Context: "AttachDevice(Bstr(pszCtl).raw(), port, device, DeviceType_HardDisk, pMedium2Mount)" at line 766 of file VBoxManageStorageController.cpp
```

I'm currently working around this with:
```
vagrant plugin install vagrant-persistent-storage --plugin-version 0.0.21
```

**Comment by kusnier** [comment]
Fixed with v0.0.23

Thanks you!

**Comment by mradcliffe** [comment]
No, this didn't fix the issue.

You can still run into the problem because the values are `0` and `1` yet the commit that this was fixed in sets the value to `2`.

**Comment by kusnier** [comment]
Sorry. You are right. I have to test more.

Thank you. Fixed with v0.0.24
